# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
# After generation, this file was copied to enable v0.2.x installations of the command line tool.
class DepscloudCliAT02X < Formula
  desc "Command line interface to the deps.cloud API"
  homepage "https://deps.cloud/"
  version "0.2.34"

  if OS.mac?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.34/deps_0.2.34_darwin_amd64.tar.gz"
    sha256 "d855894fb708f0040f133531a380797e763c8de03d4231c97775604f12b9a1fe"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.34/deps_0.2.34_linux_amd64.tar.gz"
    sha256 "db894946b9d326544e3ef4e706c11c962dc1881f8e87d4034d8c738aa634fb18"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.34/deps_0.2.34_linux_armv7.tar.gz"
    sha256 "70493d0402e8f75c55b401cdc24e78740883b25171ddf0c40325f5666c57646d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.34/deps_0.2.34_linux_arm64.tar.gz"
    sha256 "6215bf50f351a051d6e5dc4f7f1bd317c7199c0fb76c421c0b5e6f502942b066"
  end

  def install
    bin.install "deps"
  end
end
