# This file was generated by GoReleaser. DO NOT EDIT.
class DepscloudCli < Formula
  desc "Command line interface to the deps.cloud API"
  homepage "https://deps.cloud/"
  version "0.2.25"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.25/deps_0.2.25_darwin_amd64.tar.gz"
    sha256 "0149abac78a95599130c8f35271267085db277e505ca8b5f91151dccaae3ffad"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/depscloud/depscloud/releases/download/v0.2.25/deps_0.2.25_linux_amd64.tar.gz"
      sha256 "8695f9e156923b1d03113b7e77453f52258c70070390570e2c820ba9c12c1d8c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/depscloud/depscloud/releases/download/v0.2.25/deps_0.2.25_linux_arm64.tar.gz"
        sha256 "8f4c3dfe22f55558e348018d096fafd89811ede76048c819faeb3b71ed8cd2b4"
      else
        url "https://github.com/depscloud/depscloud/releases/download/v0.2.25/deps_0.2.25_linux_armv7.tar.gz"
        sha256 "0505d3d7372ba5d1d1058d1e0b77f9f5dd87d1a3409c546f80cb58e34be532e9"
      end
    end
  end

  def install
    bin.install "deps"
  end
end
