# This file was generated by GoReleaser. DO NOT EDIT.
class DepscloudCli < Formula
  desc "Command line interface to the deps.cloud API"
  homepage "https://deps.cloud/"
  version "0.2.32"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/depscloud/depscloud/releases/download/v0.2.32/deps_0.2.32_darwin_amd64.tar.gz"
    sha256 "8b5faf28c80e31ab21ef1c026d8f7adf85d58843d9bfa7a25862d636c20bec07"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/depscloud/depscloud/releases/download/v0.2.32/deps_0.2.32_linux_amd64.tar.gz"
      sha256 "f8599910e78197127b65422dde1cb615ae8d44b9731c8a979ebba8e6003816e2"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/depscloud/depscloud/releases/download/v0.2.32/deps_0.2.32_linux_arm64.tar.gz"
        sha256 "5ca7affc235f2c96f01d0f153a0560f867e2c3a4feafd4247a5ba4aca9b9bdb6"
      else
        url "https://github.com/depscloud/depscloud/releases/download/v0.2.32/deps_0.2.32_linux_armv7.tar.gz"
        sha256 "4a1c621b8d19a2a6388237f051b576c825cb9539db6f9bfece2139531fe9e72b"
      end
    end
  end

  def install
    bin.install "deps"
  end
end
